---
# gpiopins = [4, 17, 18, 21, 22, 23, 24, 25]

host: 192.168.1.243
port: 5012


# ┌────────── minute (0 - 59)
# │ ┌──────── hour (0 - 23)
# │ │ ┌────── day of month (1 - 31)
# │ │ │ ┌──── month (1 - 12)
# │ │ │ │ ┌── day of week (0 - 6 => Sunday - Saturday, or
# │ │ │ │ │                1 - 7 => Monday - Sunday)
# | | | | | |- Year
# ↓ ↓ ↓ ↓ ↓ v
# * * * * * * command to be executed

schedules: 
  #every_other_day:
  #  duration: 10
  #  cron: "0 20 2-30/2 * * *"
  #  zones: [ 1, 2, 3 ,4 ,5]
  mon_wed_fri_morning:
    duration: 15
    cron: "30 6 * * 1,3,5 *"
    zones: [ 1, 2, 3 ,4 ,5]
  mon_wed_fri_evening:
    duration: 15
    cron: "0 23 * * 1,3,5 *"
    zones: [ 1, 2, 3 ,4 ,5]
  twice_week:
    cron: "0 20 * * 2,6 *"
    duration: 30 
    zones: [ 6 ]
  everyday:
    cron: "0 21 * * * *"
    duration: 10
    zones: [ 7 ]

lawn:
  zone1:
    description: "Turf front"
    pin: 4
  zone2:
    description: "Turf near aspens"
    pin: 17
  zone3:
    description: "Turf near maples and garden"
    pin: 18
  zone4:
    description: "Turf near patio"
    pin: 27
  zone5: 
    description: "Turf center lawn"
    pin: 22
  zone6:
    description: "Drip trees and front bed"
    pin: 23
  zone7:
    description: "Drip garden"
    pin: 24
  zone8:
    description: "unused"
    pin: 25
